In [4]:
import numpy as np

In [2]:
turns = 1
no_of_players = 2
nodes_per_branch = 3
min_val = 1
max_val = 20

In [3]:
np.random.randint(min_val, max_val, (9, ))

array([17,  8, 10,  6, 10,  5, 18, 12, 10])

In [4]:
depth = turns * no_of_players
print("Depth:", depth)
print("Branch:", nodes_per_branch)
terminal_state = nodes_per_branch ** depth
print("Terminal States (Leaf Nodes):", terminal_state)

Depth: 2
Branch: 3
Terminal States (Leaf Nodes): 9


In [5]:
graph = [[],
         [],
         [],
         [],
         ]

In [6]:
''' THE GRAPH Structure
---------------------0----------------------
---------1-----------2-------------3--------
------4--5--6----7---8---9----10--11---12---





'''

' THE GRAPH Structure\n---------------------0----------------------\n---------1-----------2-------------3--------\n------4--5--6----7---8---9----10--11---12---\n'

In [5]:
graph = np.array([[0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
                  [1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                  [1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
                  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
                  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
                  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
                  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]], np.int32)


In [6]:
graph

array([[0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
visited = np.zeros(13)
visited

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [74]:
graph = np.array([[0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
                  [1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                  [1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
                  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
                  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
                  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
                  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]], np.int32)


import math

maxEval = -math.inf
minEval = math.inf
evall = 0
maxEval = 0
minEval = 0
num = 0

visited = np.zeros(13)
ans = []
stack = []


def stack_display():
    for val in stack:
        print(val, end="|")
    print()

def dfs(n, depth, maximizing_player):
    global maxEval
    global minEval
    global evall
    global num

    if visited[n] != 0:
        pass
    else:
        if(depth == 0):
            print(values[n])
            return values[n]
        
        if(maximizing_player == True):
            visited[n] = 1
            stack.append(n)
            stack_display()
            num = 0
            for relation in graph[n]:
                if relation != 0:
                    evall = dfs(num, depth - 1, False)
                    maxEval = max(evall, maxEval)
                num = num + 1
            return maxEval
        else:
            visited[n] = 1
            stack.append(n)
            stack_display()
            num = 0
            for relation in graph[n]:
                if relation != 0:
                    evall = dfs(num, depth - 1, True)
                    minEval = min(evall, minEval)
                num = num + 1
            return minEval

src_node = int(0)


In [75]:
dfs(0, 2,  True)

0|
0|1|


TypeError: '<' not supported between instances of 'int' and 'NoneType'

In [10]:
values = {0: 0, 1: 0, 2: 0, 3: 0, 4: 3,
          5: 12, 6: 8, 7: 2, 8: 4, 9: 6,
          10: 14, 11: 5, 12: 2}
values[6]

8

In [18]:
visited

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
visited = np.zeros(13)
ans = []
stack = []

def stack_display():
    for val in stack:
        print(val, end="|")
    print()








def dfs(n):
    if visited[n] != 0:
        return
    else:
        visited[n] = 1
        stack.append(n)
        stack_display()
        num = 0
        for relation in graph[n]:
            if relation != 0:
                dfs(num)
            num = num + 1
        #print(n)
        ans.append(n)
        stack.pop()
        stack_display()

src_node = int(0)

In [17]:
dfs(0)

0|
0|1|
0|1|4|
0|1|
0|1|5|
0|1|
0|1|6|
0|1|
0|
0|2|
0|2|7|
0|2|
0|2|8|
0|2|
0|2|9|
0|2|
0|
0|3|
0|3|10|
0|3|
0|3|11|
0|3|
0|3|12|
0|3|
0|



In [13]:
graph = np.array([[0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
                  [1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                  [1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
                  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
                  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
                  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
                  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]], np.int32)






import math

maxEval = math.inf
minEval = -math.inf


visited = np.zeros(13)
ans = []
stack = []


def stack_display():
    for val in stack:
        print(val, end="|")
    print()

def dfs(n, maximizing_player):
    if visited[n] != 0:
        return
    else:
        if(maximizing_player == True):
            visited[n] = 1
            stack.append(n)
            stack_display()
            num = 0
            for relation in graph[n]:
                if relation != 0:
                    dfs(num, False)
                num = num + 1
        else:
            visited[n] = 1
            stack.append(n)
            stack_display()
            num = 0
            for relation in graph[n]:
                if relation != 0:
                    dfs(num, True)
                num = num + 1            
        #print(n)
        ans.append(n)
        stack.pop()
        stack_display()

src_node = int(0)


In [14]:
dfs(2, True)

2|
2|0|
2|0|1|
2|0|1|4|
2|0|1|
2|0|1|5|
2|0|1|
2|0|1|6|
2|0|1|
2|0|
2|0|3|
2|0|3|10|
2|0|3|
2|0|3|11|
2|0|3|
2|0|3|12|
2|0|3|
2|0|
2|
2|7|
2|
2|8|
2|
2|9|
2|



In [7]:
graph = np.array([[0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
                  [1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                  [1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
                  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
                  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
                  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
                  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]], np.int32)






import math

maxEval = math.inf
minEval = -math.inf


visited = np.zeros(13)




def dfs(n, maximizing_player):
    print(num)
    
    
    if visited[n] != 0:
        return
    else:
        if(maximizing_player == True):
            visited[n] = 1
            num = 0
            for relation in graph[n]:
                if relation != 0:
                    dfs(num, False)
                num = num + 1
        else:
            visited[n] = 1
            num = 0
            for relation in graph[n]:
                if relation != 0:
                    dfs(num, True)
                num = num + 1            

In [8]:
dfs(0, True)

0
1
0
4
1
5
1
6
1
2
0
7
2
8
2
9
2
3
0
10
3
11
3
12
3


In [1]:
dir(list())

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [7]:
x = []
x.append(1)
x.append(2)
x.append(3)
x.append(4)

In [8]:
x.pop(0)

1

In [9]:
x

[2, 3, 4]

In [12]:
print(''' THE GRAPH Structure
---------------------0----------------------\n
---------1-----------2-------------3--------\n
------4--5--6----7---8---9----10--11---12---
''')

 THE GRAPH Structure
---------------------0----------------------

---------1-----------2-------------3--------

------4--5--6----7---8---9----10--11---12---



In [15]:
one = [4, 5, 6]
two = [7, 8, 9]
three = [10, 11, 12]
zero = [one, two, three]

In [16]:
# Add a vertex to the dictionary
def add_vertex(v):
  global graph
  global vertices_no
  if v in graph:
    print("Vertex ", v, " already exists.")
  else:
    vertices_no = vertices_no + 1
    graph[v] = []

# Add an edge between vertex v1 and v2 with edge weight e
def add_edge(v1, v2, e):
  global graph
  # Check if vertex v1 is a valid vertex
  if v1 not in graph:
    print("Vertex ", v1, " does not exist.")
  # Check if vertex v2 is a valid vertex
  elif v2 not in graph:
    print("Vertex ", v2, " does not exist.")
  else:
    # Since this code is not restricted to a directed or 
    # an undirected graph, an edge between v1 v2 does not
    # imply that an edge exists between v2 and v1
    temp = [v2, e]
    graph[v1].append(temp)

# Print the graph
def print_graph():
  global graph
  for vertex in graph:
    for edges in graph[vertex]:
      print(vertex, " -> ", edges[0], " edge weight: ", edges[1])

# driver code
graph = {}
# stores the number of vertices in the graph
vertices_no = 0
add_vertex(1)
add_vertex(2)
add_vertex(3)
add_vertex(4)
# Add the edges between the vertices by specifying
# the from and to vertex along with the edge weights.
add_edge(1, 2, 1)
add_edge(1, 3, 1)
add_edge(2, 3, 3)
add_edge(3, 4, 4)
add_edge(4, 1, 5)
print_graph()
# Reminder: the second element of each list inside the dictionary
# denotes the edge weight.
print ("Internal representation: ", graph)

print(graph[])

1  ->  2  edge weight:  1
1  ->  3  edge weight:  1
2  ->  3  edge weight:  3
3  ->  4  edge weight:  4
4  ->  1  edge weight:  5
Internal representation:  {1: [[2, 1], [3, 1]], 2: [[3, 3]], 3: [[4, 4]], 4: [[1, 5]]}


In [18]:
graph[1]

[[2, 1], [3, 1]]